### ISSUE TITLE
macOS icu4c is too new

### ISSUE THREAD

**Issue by lfuelling** [brianmario/charlock_holmes#155]
Hi,
I'm getting runtime errors on macOS because `charlock_holmes` is trying to load:
- `/usr/local/opt/icu4c/lib/libicudata.64.dylib` which is now called `libicudata.67.1.dylib`
- `/usr/local/opt/icu4c/lib/libicuuc.64.dylib` which is now `libicuuc.67.1.dylib`
- `/usr/local/opt/icu4c/lib/libicui18n.64.dylib` which is now `libicui18n.67.1.dylib`
- `/usr/local/opt/icu4c/lib/libicuio.64.dylib` which is now `libicuio.67.1.dylib`

Additionally this can't be fixed by symlinking the expected files to the current ones because it can't find symbols then:

```
 Symbol not found: __ZN6icu_648ByteSink15GetAppendBufferEiiPciPi
   Referenced from: ~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/charlock_holmes-0.7.7/lib/charlock_holmes/charlock_holmes.bundle
   Expected in: /usr/local/opt/icu4c/lib/libicuuc.64.dylib
```

It would be nice if `charlock_holmes` could be updated to latest icu4c.

**Comment by lfuelling** [comment]
I was able to "fix" the errors by reinstalling ruby and all gems. I'm not sure anymore if this was an issue with `charlock_holmes `.

**Comment by hmnhf** [comment]
I did the following to fix this:

```
# Removed charlock_holmes from Gemfile
bundle clean
bundle config build.charlock_holmes --with-icu-dir=/usr/local/opt/icu4c 
bundle install
```
