### ISSUE TITLE
GitLab/charlock issues with latest libicui18n

### ISSUE THREAD

**Issue by ghost** [brianmario/charlock_holmes#48]
When instaling the gem:
unable to convert "\xD0" from ASCII-8BIT to UTF-8 for lib/charlock_holmes/charlock_holmes.so, skipping

Libs installed:
# ls /usr/lib/libicui18n.so*

/usr/lib/libicui18n.so  /usr/lib/libicui18n.so.52  /usr/lib/libicui18n.so.52.1

gitlab env info output:

$ bundle exec rake gitlab:env:info RAILS_ENV=production
rake aborted!
libicui18n.so.51: cannot open shared object file: No such file or directory - /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/charlock_holmes-0.6.9.4/lib/charlock_holmes/charlock_holmes.so

charlock_holmes wants libicui18n.so.51 !
If i link .so.51 to the actual .so as following:
# ln -s /usr/lib/libicui18n.so /usr/lib/libicui18n.so.51

the output is:

$ bundle exec rake gitlab:env:info RAILS_ENV=production
rake aborted!
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/charlock_holmes-0.6.9.4/lib/charlock_holmes/charlock_holmes.so: undefined symbol: _ZTIN6icu_518ByteSinkE - /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/charlock_holmes-0.6.9.4/lib/charlock_holmes/charlock_holmes.so

Using kernel 3.10.9, qt4 4.8.5-3, icu 52.1-1

NOTE:
if i come back to old ICU lib version:
# cd /var/cache/pacman/pkg/
# pacman -U icu-51.2-1-x86_64.pkg.tar.xz

It works great.

**Comment by brentluna** [comment]
@cbrake I'm getting this error when pushing to my heroku remote, locally everything works fine.  Any thoughts on how to resolve for heroku hosted where it handles the bundle install?
