### ISSUE TITLE
Heroku Support

### ISSUE THREAD

**Issue by dustinsgoodman** [brianmario/charlock_holmes#76]
First off, great gem. Really like how quick and powerful it is. That being said, it took me about 20 hours to come up with a good deployment plan for it on Heroku. I would have switched to EC2 or Digital Ocean if I had a choice because this issue was so bad. So here are a few issues...

1. Heroku runs Ubuntu 10.04 which only has icu4c v42 available unless you're able to run an `apt-get update` which isn't possible. This makes [Steve Tooke's solution](http://tooky.co.uk/using-charklock_holmes-on-heroku/) unusable.
2. [This solution](http://stackoverflow.com/questions/18926574/how-to-install-charlock-holmes-dependency-libicu-dev-on-heroku/22662875#22662875) uses a heroku build pack to install the correct version of icu4c into vendor and install the gem with environment variables which is cool but relies on hosting the package on s3 and maintaining said package.
3. [The bundled version of the gem](http://stackoverflow.com/questions/18926574/how-to-install-charlock-holmes-dependency-libicu-dev-on-heroku/18926982#18926982) is a completely unacceptable answer as deploys take 15+ minutes.

So is there anyway to make the gem compatible with v42 of icu4c or redesign the gem in a way that deploys to Heroku are more manageable and acceptable in terms of time?

**Comment by BM5k** [comment]
Does today’s [heroku + docker](https://blog.heroku.com/archives/2015/5/5/introducing_heroku_docker_release_build_deploy_heroku_apps_with_docker) announcement make this any easier?

**Comment by dustinsgoodman** [comment]
I stopped maintaining the app using this gem so I don't actually know. Hopefully someone else with experience can chime in on this because I have another app I would like to use this gem with but won't due to the deployment issues.

**Comment by sobrinho** [comment]
I've just published a definitive guide on wiki, check [here](https://github.com/brianmario/charlock_holmes/wiki/Installing-charlock-holmes-and-libicu-dev-on-heroku).

**Comment by donnykurnia** [comment]
I'm still maintaining this Heroku buildpack:
https://github.com/donnykurnia/heroku-buildpack-ruby

I'll merge any new stable releases to kept it up-to-date.

**Comment by dustinsgoodman** [comment]
@sobrinho's wiki article worked perfectly. The multi buildpack is going away end of the year though so you'll need to update the instructions for that change but other than that good stuff. Going to close the issue because the wiki article resolved my issue.
