### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by wikimore** [brianmario/charlock_holmes#78]
install like this, gem install charlock_holmes -- --with-icu-dir=/usr/local/Cellar/icu4c

then get this error
/Users/ted/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/ted/.rvm/gems/ruby-2.0.0-p451@global/extensions/x86_64-darwin-12/2.0.0-static/charlock_holmes-0.7.3/charlock_holmes/charlock_holmes.bundle, 9): Library not loaded: @@HOMEBREW_PREFIX@@/opt/icu4c/lib/libicudata.53.1.dylib (LoadError)
  Referenced from: /Users/ted/.rvm/gems/ruby-2.0.0-p451@global/extensions/x86_64-darwin-12/2.0.0-static/charlock_holmes-0.7.3/charlock_holmes/charlock_holmes.bundle
  Reason: image not found - /Users/ted/.rvm/gems/ruby-2.0.0-p451@global/extensions/x86_64-darwin-12/2.0.0-static/charlock_holmes-0.7.3/charlock_holmes/charlock_holmes.bundle

why load icu4c lib from @@HOMEBREW_PREFIX@@/opt/icu4c/lib/ ？

**Comment by jzk** [comment]
This helped me as well. Thanks

**Comment by louis-she** [comment]
Works like a charm! 💯

**Comment by justin808** [comment]
Solved for me by running the instructions in the README.md for brew:

`bundle config build.charlock_holmes --with-icu-dir=/usr/local/opt/icu4c`

then 

`bundle`

**Comment by Dorian** [comment]
`gem install charlock_holmes` worked here :) (Can't believe this is ~3 years old :) )

**Comment by vijaim** [comment]
Awesome `gem install charlock_holmes` works. Thanks

**Comment by cagmz** [comment]
Thank you @chengguangnan

**Comment by radicalsauce** [comment]
Still works!

**Comment by fatihacet** [comment]
Coming from 2021 and still works!

**Comment by jeyip** [comment]
Thanks @chengguangnan 

Still works

**Comment by Awlter** [comment]
comming from 2022, still works lol

**Comment by naveedHashmi** [comment]
comming from 2023, still works. Thanks @chengguangnan
