### ISSUE TITLE
 Problem with installing 0.6.9.4 in linux (opensuse)

### ISSUE THREAD

**Issue by helper2424** [brianmario/charlock_holmes#93]
I am trying to install gitlab v7.8.4 without omnibus. Gitlab hasn't omnibus for opensuse and i am isntalling it's manually. When bundler install charlock_holmes it's get error:

> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.> 

>     /usr/local/rvm/rubies/ruby-2.0.0-p576/bin/ruby extconf.rb 
> checking for main() in -licui18n... yes
> checking for main() in -licui18n... yes
> checking for unicode/ucnv.h... yes
>   -- tar zxvf file-5.08.tar.gz
>   -- ./configure --prefix=/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/charlock_holmes-0.6.9.4/ext/charlock_holmes/dst/ --disable-shared --enable-static --with-pic
>   -- patch -p0 < ../file-soft-check.patch
>   -- make -C src install
>   -- make -C magic install
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.> 

> Provided configuration options:
> 	--with-opt-dir
> 	--without-opt-dir
> 	--with-opt-include
> 	--without-opt-include=${opt-dir}/include
> 	--with-opt-lib
> 	--without-opt-lib=${opt-dir}/lib64
> 	--with-make-prog
> 	--without-make-prog
> 	--srcdir=.
> 	--curdir
> 	--ruby=/usr/local/rvm/rubies/ruby-2.0.0-p576/bin/ruby
> 	--with-icu-dir
> 	--without-icu-dir
> 	--with-icu-include
> 	--without-icu-include=${icu-dir}/include
> 	--with-icu-lib
> 	--without-icu-lib=${icu-dir}/
> 	--with-icui18nlib
> 	--without-icui18nlib
> 	--with-icui18nlib
> 	--without-icui18nlib
> /usr/local/rvm/rubies/ruby-2.0.0-p576/lib64/ruby/2.0.0/fileutils.rb:1552:in `stat': No such file or directory - /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/charlock_holmes-0.6.9.4/ext/charlock_holmes/dst/lib/libmagic.a (Errno::ENOENT)
> 	from /usr/local/rvm/rubies/ruby-2.0.0-p576/lib64/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
> 	from /usr/local/rvm/rubies/ruby-2.0.0-p576/lib64/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
> 	from /usr/local/rvm/rubies/ruby-2.0.0-p576/lib64/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
> 	from /usr/local/rvm/rubies/ruby-2.0.0-p576/lib64/ruby/2.0.0/fileutils.rb:393:in `cp'
> 	from extconf.rb:67:in `<main>'> 

> extconf failed, exit code 1> 

> Gem files will remain installed in /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/charlock_holmes-0.6.9.4 for inspection.
> Results logged to /home/git/gitlab/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0/charlock_holmes-0.6.9.4/gem_make.out

Installer undefined libmagic.a, because search it here ext/charlock_holmes/dst/lib/ , but in my server it's here ext/charlock_holmes/dst/lib64/. To fix problem need change in ext/charlock_holmes , line 67:
`FileUtils.cp "#{CWD}/dst/lib/libmagic.a", "#{CWD}/libmagic_ext.a"`
to 
`FileUtils.cp "#{CWD}/dst/lib64/libmagic.a", "#{CWD}/libmagic_ext.a"`

I fix it, but when bundler install gems, it's remove my changes. Need help. My configuration:

openSUSE 13.1 (Bottle) (x86_64)
rvm 1.25.33 (stable)

**Comment by pndiku** [comment]
You need to unset the "CONFIG_SITE" variable.

`unset CONFIG_SITE`

Then the bundle will install

**Comment by tiq-dbl** [comment]
Solution works for me. How ever an update of charlock_holmes whould be great.
@randx: I whould like this work around will be recorded in the update documents.

**Comment by helper2424** [comment]
Yep, it's help, thanks.
